title: Just the Docs Template
description: A sample documentation site using Just the Docs theme
theme: just-the-docs

url: https://just-the-docs.github.io

permalink: pretty

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# logo: "/assets/images/logo.webp"

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: "k"

# For copy button on code
enable_copy_code_button: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"

# Enable MathJax for LaTeX support
math: mathjax
  
aux_links:
  Github: https://github.com/NodesAutomations/TemplateJustTheDoc

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/NodesAutomations/Template_JustTheDoc" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: nil

# Callouts
callouts_level: quiet # or loud
callouts:
  tip:
    title: Tip
    color: green
  info:
    title: Info
    color: blue
  warning:
    title: Warning
    color: yellow
  danger:
    title: Danger
    color: red

